name: CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '56 5 * * 1'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

          
      - name: Display CodeQL Configuration
        run: |
          cat /home/runner/.config/codeql/config || echo "No config file found"

      - name: Check available disk space
        run: df -h
