name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      USERNAME: logan2507
      PASSWORD: 10qpalzm@
      GITHUB_REPO: JIVASROHITH/docker

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    - name: Push to Docker Hub
      run: docker push my-image-name:$(date +%s)
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "JIVASROHITH"
        git config --global user.email "jivasrohith@karunya.edu.in"
        git remote add origin https://github.com/${GITHUB_REPO}.git
        git push --force origin main:gh-pages
