name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: logan2507
        password: 10qpalzm@
    - name: Push to Docker Hub
      run: docker push my-image-name:$(date +%s)
    - name: Deploy to GitHub Pages
      uses: actions/checkout@v4
      run: |
        git config --global user.name "JIVASROHITH"
        git config --global user.email "jivasrohith@karunya.edu.in"
        git remote add origin https://github.com/JIVASROHITH/docker.git
        git push --force origin main:gh-pages
